name: Compile PDF for gh-pages

on:
  push:
    branches:
      - main

jobs:
  compile-latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nixbuild/nix-quick-install-action@v27

      - name: Build PDF
        run: nix build

      - name: Deploy PDF
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: result/
          keep_files: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'compile pdf:'
